package bisq.rpccalls;

import bisq.proto.grpc.CreatePaymentAccountRequest;
import bisq.proto.grpc.PaymentAccountsGrpc;
import io.grpc.ManagedChannelBuilder;

import static java.lang.System.out;

public class CreatePaymentAccount extends BaseJavaExample {

    public static void main(String[] args) {
        try {
            var channel = ManagedChannelBuilder.forAddress("localhost", 9998).usePlaintext().build();
            addChannelShutdownHook(channel);
            var credentials = buildCallCredentials(getApiPassword());
            var stub = PaymentAccountsGrpc.newBlockingStub(channel).withCallCredentials(credentials);
            // Fill in the swift payment account json form generated by GetPaymentAccountForm.
            var request = CreatePaymentAccountRequest.newBuilder()
                    .setPaymentAccountForm("/path/to/swift.json")
                    .build();
            var response = stub.createPaymentAccount(request);
            out.println("New swift payment account: " + response.getPaymentAccount());
        } catch (Throwable t) {
            handleError(t);
        }
    }
}
